# Use an official Node.js image as the base
FROM node:18

# Set the working directory to /app
WORKDIR /src/app

# Copy the package.json file
COPY package*.json ./

# Install dependencies
# RUN npm install

# Copy the rest of the code
COPY . .

# Build the app
RUN npm run build

# Expose the port
EXPOSE 3000

# Run the command to start the development server
CMD ["npm", "start"]
